# Site settings
title: PIV Enablement Guides
name: PIV Enablement Guides
email: icam@gsa.gov
author:
    name: FICAM
description: PIV Guidance
baseurl: '/piv-guides'

highlighter: rouge
branch: master

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /piv-guides/img/logo.png
logoalt: Federal Identity Credential and Access Management

ficam_playbooks_url: /ficam-guides/

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: piv-guides
  description: FICAM Playbook - PIV Guidance
  url: https://github.com/GSA/piv-guides

# Sidebar uses a single github repository to link to issues.
github:
  repository_url: https://github.com/GSA/piv-guides

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

navigation:
- text: Introduction
  url: ''
  internal: true
  coll: false
- text: Basics of a PIV Credential
  url: elements
  internal: true
  coll: false
- text: Getting Started
  url: start
  internal: true
  coll: false
- text: Details of a PIV Credential
  url: details
  internal: true
  coll: false
- text: Identifiers in a PIV Credential
  url: identifiers
  internal: true
  coll: false
- text: Certificate Trust for a PIV Credential
  url: pivcertchains
  internal: true
  coll: false
- text: Network Authentication
  url: networkconfig/
  internal: true
  coll: true
  collname: networkconfig
- text: Developer Guides
  url: devconfig/
  internal: true
  coll: true
  collname: devconfig
- text: User Guides
  url: userconfig/
  internal: true
  coll: true
  collname: userconfig
- text: Script and Code Samples
  url: code
  internal: true
  coll: false
- text: Contribute
  url: contribute
  internal: true
  coll: false

collections:
  networkconfig:
    label: "Network Authentication"
    permalink: /networkconfig/:path/
    output: true
  userconfig:
    label: "User Guides"
    permalink: /userconfig/:path/
    output: true
  devconfig:
    label: "Developer Guides"
    permalink: /devconfig/:path/
    output: true


include:
- _stylesheets
- _javascript



# Custom site configuration
lang: en
